onramp:
  - id: metronome
    type: metronome
    config:
      interval: 1000 # Every second

offramp:
  - id: ws0
    type: ws
    config:
      url: ws://localhost:8080/
  - id: ws1
    type: ws
    config:
      url: ws://localhost:8081/
  - id: ws2
    type: ws
    config:
      url: ws://localhost:8082/

binding:
  - id: default
    links:
      "/onramp/metronome/{instance}/out": ["/pipeline/roundrobin/{instance}/in"]
      "/pipeline/roundrobin/{instance}/ws0": ["/offramp/ws0/{instance}/in"]
      "/pipeline/roundrobin/{instance}/ws1": ["/offramp/ws1/{instance}/in"]
      "/pipeline/roundrobin/{instance}/ws2": ["/offramp/ws2/{instance}/in"]

mapping:
  /binding/default/01:
    instance: "01"
