version: '3.8'
services:
  elastic:
    image: 'elasticsearch:8'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
  kibana:
    image: 'kibana:8'
    ports:
      - '5601:5601'
    depends_on:
      elastic:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: 'http://elastic:9200'
      ELASTICSEARCH_HOSTS: http://elastic:9200
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
  tremor:
    image: tremorproject/tremor:edge
    depends_on:
      kibana:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - 4242:4242
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./etc/tremor:/etc/tremor:ro
