binding:
  - id: redpanda_elastic
    links:
      # ingest into elastic
      "/onramp/redpanda-in/{instance}/out":
        - "/pipeline/ingest/{instance}/in"
      "/pipeline/ingest/{instance}/out":
        - "/offramp/elastic-out/{instance}/in"
      "/pipeline/ingest/{instance}/err":
        - "/offramp/system::stderr/{instance}/in"

      # elastic ingest response handling
      # ok handling
      "/offramp/elastic-out/{instance}/out":
        - "/pipeline/ingest_ok_handling/{instance}/in"
      "/pipeline/ingest_ok_handling/{instance}/out":
        - "/offramp/redpanda-out/{instance}/in"
        - "/offramp/ok_stdout/{instance}/in"
      "/pipeline/ingest_ok_handling/{instance}/err":
        - "/offramp/system::stderr/{instance}/in"
      # err handling
      "/offramp/elastic-out/{instance}/err":
        - "/pipeline/ingest_err_handling/{instance}/in"
      "/pipeline/ingest_err_handling/{instance}/out":
        - "/offramp/redpanda-out/{instance}/in"
        - "/offramp/err_stderr/{instance}/in"
      "/pipeline/ingest_err_handling/{instance}/err":
        - "/offramp/system::stderr/{instance}/in"

