version: "3.8"
services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - '0M'
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - redpanda:9092
      - --advertise-kafka-addr
      - redpanda:9092
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9644/v1/status/ready"]
      start_period: 0s
      interval: 1s
      retries: 30
  tremor_in:
    image: tremorproject/tremor:0.11
    depends_on:
      - kafka
    environment:
      - SLEEP=10
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./etc/tremor_in:/etc/tremor:ro
      - ./var/log/in:/var/log/:rw
  tremor_out:
    image: tremorproject/tremor:0.11
    depends_on:
      - kafka
    environment:
      - SLEEP=20
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./etc/tremor_out:/etc/tremor:ro
      - ./var/log/out:/var/log:rw
