onramp:
  - id: rabbit-in
    type: amqp
    codec: json
    config:
      amqp_addr: "amqp://guest:guest@rabbitmq:5672/shared"
      queue_name: "tremor"

      queue_options:
        passive: true
        durable: true
        exclusive: false
        auto_delete: false
        nowait: true
      exchange: "tremor"

offramp:
  - id: ok_stdout
    type: stdout
    config:
      prefix: "[OK] "
  - id: err_stderr
    type: stderr
    config:
      prefix: "[ERR] "
