onramp:
  - id: redpanda-in
    type: kafka
    codec: json
    config:
      brokers:
        - redpanda:9092
      topics:
        - tremor
      group_id: redpanda_es_correlation
      retry_failed_events: false
      rdkafka_options:
        enable.auto.commit: false
offramp:
  - id: elastic-out
    type: elastic
    linked: true
    config:
      nodes:
        - http://elasticsearch:9200
      concurrency: 16
  - id: redpanda-out
    type: kafka
    codec: json
    config:
      brokers:
        - redpanda:9092
      group_id: tremor_out
      topic: ingest-notify
  - id: ok_stdout
    type: stdout
    config:
      prefix: "[OK] "
  - id: err_stderr
    type: stderr
    config:
      prefix: "[ERR] "
