version: '3.8'
services:
  tdengine:
    image: tdengine/tdengine:2.4.0.18
    ports:
      - '6030-6049:6030-6049'
      - '6030-6049:6030-6049/udp'
  # chronograf:
  #   image: chronograf:1.7
  #   ports:
  #     - '8888:8888'
  #   depends_on:
  #     - tdengine
  #   command: chronograf --influxdb-url=http://influxdb:8086
  telegraf:
    image: telegraf:1.22
    depends_on:
      - tdengine
      - tremor
    volumes:
      - ./config/telegraf:/etc/telegraf:ro
  tremor:
    image: tremorproject/tremor:edge
    depends_on:
      - tdengine
    ports:
      - 4242:4242
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    volumes:
      - ./config/tremor-tdengine:/etc/tremor:ro