version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - net
    healthcheck:
      test: /etc/rabbitmq_setup/configure.sh
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
       - ./etc/rabbitmq:/etc/rabbitmq_setup
  tremor_in:
    image: tremorproject/tremor:0.11
    depends_on:
     rabbitmq:
       condition: service_healthy
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./etc/tremor_in:/etc/tremor:ro
      - ./var/log:/var/log:rw
    networks:
      - net
  tremor_out:
    image: tremorproject/tremor:0.11
    depends_on:
     rabbitmq:
        condition: service_healthy
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./etc/tremor_out:/etc/tremor:ro
      - ./var/log:/var/log:rw
    networks:
      - net

volumes:
  esdata:
    driver: local

networks:
  net:
    driver: bridge

