on:
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]

name: Broken Link Check
jobs:
  check-links:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/link-checker@v1.0.1
      with:
        # Required:
        url: 'https://www.tremor.rs'
        # optional:
        honorRobotExclusions: false
        ignorePatterns: 'github,google'
        recursiveLinks: true # Check all URLs on all reachable pages (could take a while)
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"