name: Publish

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: generate stdlib
        run:  make clean all
      - name: Build docs
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build        
      - name: Deploy docs
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v2
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: build
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}